# Generated by Django 4.2 on 2023-06-21 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Meals', '0002_meal_cook_time_meal_meal_type_meal_prep_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='name',
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Meals.meal'),
        ),
    ]
