# Generated by Django 4.1.4 on 2023-07-09 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Meals', '0003_remove_recipe_name_recipe_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='meal_plan',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Meals.meal'),
        ),
    ]
