# Generated by Django 4.1.4 on 2023-07-09 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Meals', '0004_remove_meal_meal_plan_mealplan_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='meal_type',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='breakfast_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakfast_plan', to='Meals.meal'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='dinner_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dinner_plan', to='Meals.meal'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='lunch_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lunch_plan', to='Meals.meal'),
        ),
    ]
