# Generated by Django 4.1.4 on 2023-07-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meals', '0005_remove_mealplan_meal_remove_mealplan_meal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='name',
            field=models.CharField(default='blank', max_length=255),
        ),
    ]
