# Generated by Django 4.1.4 on 2023-06-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0003_alter_exercise_id_alter_workoutexercise_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
