# Generated by Django 4.1.4 on 2023-07-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0004_alter_exercise_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='workout_picture',
            field=models.ImageField(default='static\\images\\profile_pictures\\default.png', upload_to=''),
        ),
    ]
