# Generated by Django 4.1.4 on 2023-06-30 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.SmallIntegerField(default=0)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('height', models.FloatField(default=5.0)),
                ('weight', models.FloatField(default=200)),
                ('monthly_goals1', models.CharField(default='goals', max_length=1000)),
                ('monthly_goals2', models.CharField(default='goals', max_length=1000)),
                ('monthly_goals3', models.CharField(default='goals', max_length=1000)),
                ('profile_picture', models.ImageField(default='static\\images\\profile_pictures\\default.png', upload_to='')),
                ('recommended_meal', models.CharField(default='goals', max_length=1000)),
                ('recommended_workout', models.CharField(default='goals', max_length=1000)),
                ('training_level', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], default='B', max_length=1)),
                ('sleep_goals', models.CharField(default='8 hours', max_length=40)),
                ('water_goals', models.CharField(default='3 Liters', max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
