# Generated by Django 4.1.4 on 2023-07-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='images\\profile_pictures\\default.png', upload_to=''),
        ),
    ]
