# Generated by Django 4.1.4 on 2023-07-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logins', '0003_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
